### ISSUE TITLE
Is the SDK actively developed?

### ISSUE THREAD

**Issue by alecive** [ci2cv/face-analysis-sdk#9]
Hello,

I have seen that there has been no commit after Jan 2014. Is this SDK still in active development?

**Comment by linas** [comment]
Nope. However, I have merged most outstanding branches into this repo:

https://github.com/hansonrobotics/face-analysis-sdk

This includes misc fixes for Linux, a port to Windows, a port to Qt5 from Qt4, and a port to opencv version3

It works for me, but I have only tested on Ubuntu trusty with opencv2 and Qt5 -- I don't have any other kinds of machines.

I did not merge three branches 
-- one containing python bindings -- it looked very hacked
-- one containing an automated emotion detector
-- one containing a hand-built emotion detector.

These did not appear to be ready-to-merge.

**Comment by alecive** [comment]
Thank you @linas for the answer!

**Comment by zhaishengfu** [comment]
thanks @linas . Do you know how to use own trained data for face tracker? I see thant there are many face binary files and do not know how to generate them

**Comment by linas** [comment]
Hi @zhaishengfu I have not touched this in years, and do not recall any details. Sorry.
